I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
Traceback (most recent call last):
  File "train_model.py", line 499, in <module>
    tf.app.run()
  File "/hpc/sw/python-2.7.11/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train_model.py", line 446, in main
    train_siamese()
  File "train_model.py", line 234, in train_siamese
    loss = s.loss(channel1, channel2, y, FLAGS.margin)
  File "/nfs/home5/gdemo008/dl3/practical_3/siamese.py", line 95, in loss
    right_part = tf.mul((1 - label), tf.maximum(0., margin - d))
NameError: global name 'd' is not defined
